### ISSUE TITLE
What do we do with world.map

### ISSUE THREAD

**Issue by fing3rguns** [GrapeshotGames/AtlasTerritoryMap#1]
As title states, it seems to be generating fine here but there is no mention of what to do with the actual files it generates and linking it to the in-game map?

**Comment by GrapeshotGames** [comment]
Long as you have the host setup it does it all for you. Redis gets updates on those urls and pushes them down to the game clients. They download them as it updates/changes. :)

**Comment by GrapeshotGames** [comment]
This is just it running locally for a quick test.
![image](https://user-images.githubusercontent.com/45831658/50803566-29700380-12b8-11e9-9c35-9dad13ae9858.png)

**Comment by BaradineAllawa** [comment]
But what if you host your cellimgs via MetaWorldURL.... I can't use the ServerGrid folder. Simply doesn't work (never has). Will it still push to gameclients then?

**Comment by GrapeshotGames** [comment]
It only is the overlay image. Not the map images themselves so you can use MetaWorldURL or the other method. It's a different layer used in game (two actually one for enemy territories and one for your own) in the map material itself.  

Also this doesn't have to run next to the game at all. For example we have ours running on a different box. Hope this helps!

**Comment by fing3rguns** [comment]
odd mines running and can see it generating. But in-game the map doesn't have any flag data getting pushed to the clients. This is hosted on the same box as the servers.  Would the servers need a restart before it becomes active or doesn't this matter? Even have the port open for the client, but still nothing :( edit#2  Solved! opened both UDP and TCP and it now works.

**Comment by smooreace** [comment]
This isnt a support forum!!

**Comment by fing3rguns** [comment]
It's an issue with the readme TBH says nothing about opening the ports... don't be soo jaded
