### ISSUE TITLE
GridSize

### ISSUE THREAD

**Issue by nimda2** [GrapeshotGames/AtlasTerritoryMap#2]
I have not the normal Gridsize
config.json

`    "GridSize": 1200000.0,
    "ServersX": 2,
    "ServersY": 3,
    "GameSize": 4096,
    "TileSize": 256,
    "MaxZoom": 7,
    "LandRadiusUE": 10000,
    "WaterRadiusUE": 21000,
    "CircleAlpha": 128,`

ServerGrid.json

`  "BaseServerArgs": "",
  "gridSize": 1200000.0,
  "totalGridsX": 2,
  "totalGridsY": 3,
  "bUseUTCTime": false,
  "columnUTCOffset": 0.0,
  "Day0": "2018-12-30 20:00:00",
  "globalTransitionMinZ": 0.0,
  "AdditionalCmdLineParams": "",
  "OverrideShooterGameModeDefaultGameIni": {},
  "globalGameplaySetup": "",
  "coordsScaling": 0.000260122877,`

Editor:
Cell Image Size
2048

Atlas Image Size
4096

![screenshot 2019-01-08 13 15 36](https://user-images.githubusercontent.com/46486386/50830263-9bdbf480-1347-11e9-84b4-a8f40d35345e.png)

**Comment by smooreace** [comment]
So whats the bug or issue?

**Comment by nimda2** [comment]
the issu is , not all using 2x2 4x4 15x15,
or the Size 1400000

thus it is not possible to use it
an adaptation of the files for the calculation would be nice

**Comment by smooreace** [comment]
Thats why there is a config file. Works perfectly other than the slight
skewing for non-square maps. But even that isnt terrible

**Comment by GrapeshotGames** [comment]
Yea you have to set the grid size and number of cells in the config file.  Hmmm skewing you say? What is your grid size exactly? I wouldn't be surprised if there was a client side issue with some of it assuming to be square.  The image itself has to be square but we could compensate some (might be more pixels in on direction than other but shouldn't look skewed just stretched in the other direction.

**Comment by smooreace** [comment]
Sorry... I meant stretch, or squish. Currently running a 3x4. And my
comment was based on readings. I haven't got mine working yet.

**Comment by nimda2** [comment]
smooreace  you running 3x4 and it work?
i running 2x3 and i have problems, claim dots not on the claim flags
which size?

**Comment by nimda2** [comment]
GrapeshotGames
I running Size: 1200000.0 and Grids: X = 2 Y = 3
my "online map" works but ingame the Dots not over the flags these are moved 2000 meter west

**Comment by smooreace** [comment]
They clearly stated there were issues with non-square maps.

With the help of someone elses work, I have no issue with territory
placement though. But nothing is showing up that should be

**Comment by erkrystof** [comment]
Hi Grapeshot - I've never used GO but took a stab at the patch I made locally to fix oblong rectangular grids.  This at least demonstrates the spirit of the idea behind what could fix non-square maps.

https://krystof.io/setting-up-claim-markers-on-an-atlas-dedicated-server/

**Comment by GrapeshotGames** [comment]
We will have to check that one out, feel free to submit a pullrequest! The in game map I think a client side fix would be better but that doesn't help a slippy map version or something we will try to get out to you guys soon called the AtlasMapViewer.

**Comment by erkrystof** [comment]
We'll look forward to that - there's plenty of reverse engineering of the official dynamic map we've been using to generate the dedicated server maps and generic claim bubbles (as tribe data would need additional coding to populate the JSON the official maps utilize.)

**Comment by erkrystof** [comment]
Well, pull request submitted, just popped my 'Git-Pull-Request' cherry. :)

**Comment by GrapeshotGames** [comment]
Thanks a bunch for the PR! I went ahead and cleaned up some of that old cruft in there and took your same concept to account for it. Let me know if this still seems to work for you.

**Comment by erkrystof** [comment]
Works for me!  Thank you!

**Comment by upperking** [comment]
GooberGrape: would it be possible to show the company names also when mouse over-ring the ships?
[4:39 PM] GooberGrape: that way there's no confusing of same color ships not being from the same company
[4:39 PM] MrKrystof: I believe it would.  The UI gets both pieces of data (tribe name and ids), so it would just need to match the two up
[4:39 PM] MrKrystof: You could probably make a request on the git-hub wiki for Grapeshot and see what they say
[4:40 PM] GooberGrape: it would make it more us full that way rather then guessing what ships are owned by what company
[4:40 PM] MrKrystof: I agree!
