### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by MapleBaconPancake** [GrapeshotGames/AtlasTerritoryMap#3]
After following the short tutorial on the main page here i got this error  

https://gyazo.com/2b47fe2bbef8ed92ed71ac32bc38af1d

**Comment by smooreace** [comment]
You obviously didnt modify the config file

**Comment by MapleBaconPancake** [comment]
i absolutely modified the config

**Comment by smooreace** [comment]
The errors are pretty clear... the PW is wrong, or it's not seeing the DB. This isn't a bug. It's user error. And this is not a support forum.

**Comment by MapleBaconPancake** [comment]
and  you're rude and sound quite pretentious  "obviously" and "errors are pretty clear"      come off the high horse mate,    I'm just lookin for a tip,  not someone to belittle me.     maybe you should just refrain from replying next time

**Comment by smooreace** [comment]
No... Im right!

**Comment by GrapeshotGames** [comment]
@MapleBaconPancake That looks like it can't talk to your redis database. 

```
    "DatabaseConnections": [
        {
          "Name": "Default",
          "URL": "localhost",       //This will usually be your ip if not local, e.g., "1.2.3.4"
          "Port": 6379,
          "Password": "foobared"    //<--- Make sure this is your redis password
        },
        {
          "Name": "TerritoryDB",
          "URL": "localhost",        //This will usually be your ip if not local, e.g., "1.2.3.4"
          "Port": 6379,
          "Password": "foobared"     //<--- Make sure this is your redis password
        }
    ],
```

Hopefully this helps! Also make sure you can reach redis from where you run this. Sometimes that port will be locked down. But given the message it sounds like password itself isn't lining up.

**Comment by MapleBaconPancake** [comment]
ty grapshot :) update:  the passwords do lineup,  going to try to unlock the port

**Comment by GrapeshotGames** [comment]
When you unblock the port I usually recommend only doing so for your range of servers that can connect to it. Just keeps things a little more secure. Hopefully all good now!

**Comment by GrapeshotGames** [comment]
I'm going to assume that was it or it's all good now and close this issue. :)
