### ISSUE TITLE
Claim markers not showing

### ISSUE THREAD

**Issue by smooreace** [GrapeshotGames/AtlasTerritoryMap#4]
I started with a modified territoryserver.go file from MrCrystof. I had a few typos that prevented a proper recompile, but the process started anyway. After fixing those errors and again recompiling I can now see MY territories, but they are only highlighted circles. There is no green color to them. I didn't think this was correct so I went back to the original AtlasTerritoryMap.exe and territoryServer.go files, ensured the config.json file was correct, and deleted the world.map file. Launching the process led to what we would expect in the process window, but again, I could only see my territories the same way as before. 

All of this is in a fairly established 3x4 map with approximately 150 active players run on my own hardware

**Comment by erkrystof** [comment]
To further augment the discussion - the patch I walked smoorace through was to adjust for oblong rectangular grids.  Just some extra X/Y calculations.  I asked him to revert back to the original to further diagnose the issue with not all claim bubble showing.  I'm wondering if there's a defunct tribe or claim marker that stops the iterations across the markers retrieved from redis, but that's just conjecture.  I'm unable to reproduce this personally, though I'm using fresh wipes (no pun intended).

**Comment by GrapeshotGames** [comment]
I think It's just the non uniform part that is making this weird? `cheat givefow` can also be helpful to debug if it's moved around while you are an admin on that server. Note you might have to do it twice.

**Comment by smooreace** [comment]
Tried `cheat giveflo` in-game and didn't get anything noticeable beyond a game lockup for about 5 seconds. What should I be expecting? I'de love to get you more useful info to help get this resolved. but don't know what to offer

**Comment by GrapeshotGames** [comment]
On your pc that is running AtlasGame.exe can you download and install something like https://www.telerik.com/fiddler Fiddler. After you connect pull up your map and save that capture out. You will see requests out to the url that has some url like `http://1.2.3.4:8881/gameTiles/world.map`  try placing a flag and waiting 15 seconds or what ever your interval is. The client should try again then. If there are some errors connecting to the other one it might be that port being open. If you don't see the request at all then output from your AtlasTerritoryMap would be helpful.

**Comment by smooreace** [comment]
It appears that the most recent update to AtlasTerritoryMap seems to have solved the issues I was having.
