### ISSUE TITLE
Need tribe information

### ISSUE THREAD

**Issue by sakurasammi** [GrapeshotGames/AtlasTerritoryMap#5]
Disregard

**Comment by sakurasammi** [comment]
I got the map working on a website, how can I get the tribe information? 

https://www.atlasplayers.com

**Comment by smooreace** [comment]
You didnt follow the poorly worded instructions. And this isnt a support
forum

**Comment by smooreace** [comment]
You dont. This has nothing to do with a website. Its for the internal map
in the game. And this isnt a support forum

**Comment by erkrystof** [comment]
The gameGeneration of the utility is for the in-game map it seems, while the 'tileGeneration' option, which is disabled by default, is for what @sakurasammi is referencing.  It would appear to support both.

**Comment by GrapeshotGames** [comment]
The tileGeneration is for something else coming out soon which is similar to https://map.playatlas.com/ . It generates a slippy style map of the territory overlay for use by other things. I'm not sure what you want with tribe information? Are you just trying to do more like our public map? The claim flag data does have the owner id which can be a tribe or player id.  You can also query redis for more info on the tribe if you like. A small hint to you if you only want tribe stuff is knowing that tribe ids are all greater than `> 1000000000 + 50000`

**Comment by tslagle13** [comment]
I think what @sakurasammi is asking for is the tribe data on the left-hand side. We only get "tribe data coming soon" but the map.playatlas.com gets the large tribe data. Can we also get that information? I see in the map generation js there is a lookup for the tribe data but I don't know in what format it needs to be or if the generator can do that for us?

Or are you guys manually generating the tribe list data on map.playatlas.com?

**Comment by sakurasammi** [comment]
> The tileGeneration is for something else coming out soon which is similar to https://map.playatlas.com/ . It generates a slippy style map of the territory overlay for use by other things. I'm not sure what you want with tribe information? Are you just trying to do more like our public map? The claim flag data does have the owner id which can be a tribe or player id. You can also query redis for more info on the tribe if you like. A small hint to you if you only want tribe stuff is knowing that tribe ids are all greater than `> 1000000000 + 50000`

I do have the map working similar to the map.playatlas.com and yes, I want to ability to have those top tribe information, but I'm not sure how we can generate the flags .png and tribe names to go with the tribe data box.

**Comment by GrapeshotGames** [comment]
I think you guys should check out this brand new https://github.com/GrapeshotGames/AtlasMapViewer it has some of the things you are talking about! It's not exactly the one we use for map.playatlas.com but it is very similar and even has a little more in realtime. Do note it is experimental and just trying to show more of what you can do by talking to Redis DB some. Eventually we will likely merge the two but this one is much simpler to deal with. :)
