### ISSUE TITLE
ship color confusion of what company has ownership.

### ISSUE THREAD

**Issue by upperking** [GrapeshotGames/AtlasTerritoryMap#7]
Would it be possible to show the company names also when mouse overing the ships?
that way there's no confusing of same color ships not being from the same company.
It would make it more usefull that way rather then guessing what ships are owned by what company.

**Comment by GrapeshotGames** [comment]
The AtlasTerritoryMap is only the claim overlay. Did you mean to put this on https://github.com/GrapeshotGames/AtlasMapViewer ? :)

If so yes you can change what information is displayed for tooltips if you would like.
